services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: admin-portal
    networks:
      - botnet
    ports:
      - 5432:5432
  database:
    image: docker.io/paulrenenichols/database-setup
    depends_on:
      - postgres 
    build:
      context: .
      dockerfile: Dockerfile.database
    networks:
      - botnet
    environment:
      DATABASE_URL: postgresql://postgres:example@postgres:5432/admin-portal
  server:
    image: docker.io/paulrenenichols/nest-api-server
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      DATABASE_URL: postgresql://postgres:example@postgres:5432/admin-portal
    networks:
      - botnet
    ports:
      - 3000:3000
networks:
  botnet:
    driver: bridge
