FROM node:20.13.1-alpine AS base

RUN corepack enable
RUN corepack prepare yarn@stable --activate

FROM base AS runner

ENV NODE_ENV=production

ENV PORTAL_PATH=services/portal

WORKDIR /app

COPY yarn.lock .
COPY package.json .
COPY ./${PORTAL_PATH} ./${PORTAL_PATH}

RUN yarn install

EXPOSE 3000

RUN yarn run portal:build

CMD ["yarn", "run", "portal:start"]