services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: admin-portal
    networks:
      - botnet
    ports:
      - 5432:5432
  server:
    image: docker.io/paulrenenichols/nest-api-server
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      DATABASE_URL: postgresql://postgres:example@localhost:5432/admin-portal
    networks:
      - botnet
    ports:
      - 3000:3000
networks:
  botnet:
    driver: bridge
